### ISSUE TITLE
README.md may include instructions to use windows admin tools instead of modifying registry

### ISSUE THREAD

**Issue by JaimeChavarriaga** [troytse/wsl-autostart#1]
The README.md suggests an installation that modify the windows registry. Instead of that option, it is possible to configure Windows 10 to run a program when the computer starts using a startup policy or a scheduled task using administrative tools.

* Using `gpedit.msc`, it is possible to define a program that run when the computer starts
  * Note that the configured program will run as the `SYSTEM`user. 
* Using `taskschd.msc`, it is possible to schedule a task after the startup of the computer.
  * You may configure which user will run the program, a delay before run and a number of retries.
  * the same `taskschd.msc` program will show a specific log regarding the execution of the task

In addition, note that the [scheduled task can be created programmatically](https://blogs.technet.microsoft.com/heyscriptingguy/2014/05/14/use-powershell-to-create-job-that-runs-at-startup/) using Powershell. An user may run a `.ps1` script to installs the `wsl-autostart` as a scheduled task very easily.

**Comment by troytse** [comment]
Thanks for your suggestions,
I will add these features in next time :)
